@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzcyODA1NzksInN1YiI6M30.Dwc2uUmPITmoSHO3fVC7WlqZ82ywc_ta1AORVUzmOSw
###
GET http://localhost:3000/api/v1/tasks HTTP/1.1
Authorization: Bearer {{token}}
###
GET http://localhost:3000/api/v1/tasks/1 HTTP/1.1
Authorization: Bearer {{token}}
###
POST http://localhost:3000/api/v1/tasks HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "learn idiomatic go",
    "description": "learn idiomatic go to build efficient and maintainable code",
    "user_id": 3
}
###
PATCH http://localhost:3000/api/v1/tasks/3 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description": "Learn idiomatic go to build efficient and maintainable code"
}
###
DELETE http://localhost:3000/api/v1/tasks/1 HTTP/1.1
